#!/usr/bin/python

import rospy
from geometry_msgs.msg import PointStamped

def callback(msg):
    resolution = rospy.get_param('/move_base/global_costmap/resolution')
    rospy.loginfo("%d,%d", msg.point.x/resolution, msg.point.y/resolution)

if __name__ == '__main__':
    rospy.init_node('point_to_cell')
    rospy.Subscriber('clicked_point', PointStamped, callback)
    rospy.spin()

